const dummyData = {
    data: [
      {
        id: "bitcoin",
        name: "Bitcoin",
        symbol: "BTC",
        icon: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
        price: 62000,
        change24h: "+3.2%",
        marketCap: "1.2T",
        volume24h: "32B",
      },
      {
        id: "ethereum",
        name: "Ethereum",
        symbol: "ETH",
        icon: "https://cryptologos.cc/logos/ethereum-eth-logo.png",
        price: 3500,
        change24h: "+2.5%",
        marketCap: "420B",
        volume24h: "18B",
      },
      {
        id: "cardano",
        name: "Cardano",
        symbol: "ADA",
        icon: "https://cryptologos.cc/logos/cardano-ada-logo.png",
        price: 0.52,
        change24h: "-1.2%",
        marketCap: "18B",
        volume24h: "1.5B",
      },
      {
        id: "solana",
        name: "Solana",
        symbol: "SOL",
        icon: "https://cryptologos.cc/logos/solana-sol-logo.png",
        price: 140,
        change24h: "+4.1%",
        marketCap: "60B",
        volume24h: "8B",
      },
      {
        id: "ripple",
        name: "XRP",
        symbol: "XRP",
        icon: "https://cryptologos.cc/logos/xrp-xrp-logo.png",
        price: 0.65,
        change24h: "+0.9%",
        marketCap: "30B",
        volume24h: "2.3B",
      },
      {
        id: "dogecoin",
        name: "Dogecoin",
        symbol: "DOGE",
        icon: "https://cryptologos.cc/logos/dogecoin-doge-logo.png",
        price: 0.15,
        change24h: "+6.5%",
        marketCap: "20B",
        volume24h: "1.2B",
      },
      {
        id: "polkadot",
        name: "Polkadot",
        symbol: "DOT",
        icon: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png",
        price: 6.5,
        change24h: "-0.5%",
        marketCap: "8B",
        volume24h: "600M",
      },
      {
        id: "litecoin",
        name: "Litecoin",
        symbol: "LTC",
        icon: "https://cryptologos.cc/logos/litecoin-ltc-logo.png",
        price: 90,
        change24h: "+2.3%",
        marketCap: "6B",
        volume24h: "500M",
      },
      {
        id: "chainlink",
        name: "Chainlink",
        symbol: "LINK",
        icon: "https://cryptologos.cc/logos/chainlink-link-logo.png",
        price: 20,
        change24h: "-1.7%",
        marketCap: "10B",
        volume24h: "700M",
      },
      {
        id: "stellar",
        name: "Stellar",
        symbol: "XLM",
        icon: "https://cryptologos.cc/logos/stellar-xlm-logo.png",
        price: 0.12,
        change24h: "+0.8%",
        marketCap: "3B",
        volume24h: "250M",
      },
      {
        id: "avalanche",
        name: "Avalanche",
        symbol: "AVAX",
        icon: "https://cryptologos.cc/logos/avalanche-avax-logo.png",
        price: 40,
        change24h: "+4.5%",
        marketCap: "15B",
        volume24h: "1.5B",
      },
      {
        id: "tron",
        name: "Tron",
        symbol: "TRX",
        icon: "https://cryptologos.cc/logos/tron-trx-logo.png",
        price: 0.1,
        change24h: "+1.1%",
        marketCap: "9B",
        volume24h: "750M",
      },
      {
        id: "cosmos",
        name: "Cosmos",
        symbol: "ATOM",
        icon: "https://cryptologos.cc/logos/cosmos-atom-logo.png",
        price: 12,
        change24h: "-2.3%",
        marketCap: "4B",
        volume24h: "400M",
      },
      {
        id: "vechain",
        name: "VeChain",
        symbol: "VET",
        icon: "https://cryptologos.cc/logos/vechain-vet-logo.png",
        price: 0.025,
        change24h: "+1.8%",
        marketCap: "2B",
        volume24h: "100M",
      },
    ],
    exchangeRates: {
      USD: 1,
      EUR: 0.91,
      GBP: 0.79,
      JPY: 150,
      INR: 83,
    },
    currencySymbols: {
      USD: "",
      EUR: "€",
      GBP: "£",
      JPY: "¥",
      INR: "₹",
    },
  };
  
  export default dummyData;
  